#!/bin/sh

set -e

# Drop unchanged conffiles in deprecated location without triggering a dpkg question
# c.f. LP: #621923 and http://wiki.debian.org/DpkgConffileHandling
# BEGIN FIXME: use dpkg-maintscript-helper when my main OS supports it (dpkg > 1.15.7)

prep_mv_conffile() {
    local PKGNAME="$1"
    local CONFFILE="$2"

    [ -e "$CONFFILE" ] || return 0

    local md5sum="$(md5sum $CONFFILE | sed -e 's/ .*//')"
    local old_md5sum="$(dpkg-query -W -f='${Conffiles}' $PKGNAME | \
            sed -n -e "\' $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
    if [ "$md5sum" = "$old_md5sum" ]; then
        rm -f "$CONFFILE"
    fi
}

case "$1" in
install|upgrade)
    if dpkg --compare-versions "$2" lt "1.2-1"; then
        prep_mv_conffile pastebinit "/etc/pastebin.d/fpaste.org.conf"
        prep_mv_conffile pastebinit "/etc/pastebin.d/paste2.org.conf"
        prep_mv_conffile pastebinit "/etc/pastebin.d/pastebin.ca.conf"
        prep_mv_conffile pastebinit "/etc/pastebin.d/pastebin.com.conf"
        prep_mv_conffile pastebinit "/etc/pastebin.d/paste.debian.net.conf"
        prep_mv_conffile pastebinit "/etc/pastebin.d/paste.ubuntu.com.conf"
        prep_mv_conffile pastebinit "/etc/pastebin.d/pastie.org.conf"
        prep_mv_conffile pastebinit "/etc/pastebin.d/slexy.org.conf"
        prep_mv_conffile pastebinit "/etc/pastebin.d/stikked.com.conf"
        prep_mv_conffile pastebinit "/etc/pastebin.d/yourpaste.net.conf"
    fi
esac

# END FIXME

#DEBHELPER#

exit 0
